### ISSUE TITLE
Read pcaps from subdirectory

### ISSUE THREAD

**Issue by bmgante** [QXIP/node-webshark#8]
Noticed that pcaps under /captures subdirectories are not considered.

**Comment by lmangani** [comment]
@bmgante are you referring to the UI not displaying them or the backend not loading from subdirectories?

**Comment by bmgante** [comment]
When i run 
docker run -ti --rm -p 8085:8085 -v $(pwd)/captures:/captures webshark:latest

If i have a test,pcap on $(pwd)/captures/test.pcap it is properly loaded to UI.
if i have a pcap under $(pwd)/captures/folder1/test.pcap, the folder1 and test.pcap are not visible on UI.

Another thing, what do you recommend as process to capture traffic into captures folder? tcpdump with rotated files every minute, anything else more efficient?

**Comment by lmangani** [comment]
The file might not show, but it should be loaded fine if you correctly form the path to the file in the api request. This tool was assembled to serve our Cubro EXA8/OMNIA and QXIP Agent integrations rather than being general purpose as-is, so there are no batteries and no particular recommendations - integration will be up to your needs and preferences, and might require some patching around.
